### ISSUE TITLE
Prompt user to use ngrok on failed callback setup

### ISSUE THREAD

**Issue by stephenbinns** [cronofy/cronofy-csharp-sample-app#10]
Developers are getting confused with the `domain` app key, we should make this more clear to them we can make this better by doing:

1. Rename app-key name to something more sensible
2. Handle errors on callback setup to prompt to install and use ngrok filling in fields for local port and generating them the setting to go into web.config along with the command for ngrok

**Comment by VivekIshir** [comment]
@stephenbinns that will be good , Also i want to add one more point here , We need bit more descriptive help doc to run application .

**Comment by viswanathy** [comment]
I am able to successfully authenticate and connect my calendar only if I have logged-in to coronofy in same browser tab, if I do it in incognito mode, I am not able to connected Calendar Accounts. Is there anything wrong with this code or am I missing any thing? any help is appreciated.

**Comment by stephenbinns** [comment]
@viswanathy its probably best you contact our support at support@cronofy.com for help with account specifics.

**Comment by CronofyMatt** [comment]
Hi and thank you for taking the time to open this issue, and apologies for the delay in getting back. I hope that you were able to solve this issue as I understand it has been some time since it was first opened.

Due to the age of this issue I am going to close it for now, however if you are still having problems please either re-open the ticket, create a new issue, or contact us at [support@cronofy.com](mailto:support@cronofy.com) where our support and engineering teams can help you out.

We will be updating our monitoring of issues being opened on repos to make sure we don’t let issues stagnate in future. We put a lot of time and effort into the quality of our products and this falls below the standards of support and care we offer elsewhere.
